format = """
[î‚¶](#7aa2f7)\
$os\
[](bg:#7aa2f7 fg:#0b1020)\
[î‚´](bg:#a78bfa fg:#7aa2f7)\
$directory\
[î‚´](fg:#a78bfa bg:#1b2338)\
$git_branch\
$git_status\
[î‚´](fg:#1b2338 bg:#141a2a)\
$nodejs\
$rust\
$golang\
$zsh\
$vscode\
$python\
$php\
[î‚´](fg:#141a2a bg:#0b1020)\
$time\
[î‚´ ](fg:#0b1020)\
\n$character"""

[directory]
style  = "fg:#0b1020 bg:#a78bfa"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music"     = "ï€ "
"Pictures"  = "ï€¾ "
"work"      = "ğŸ—‚ï¸ "

[git_status]
style  = "fg:#0b1020 bg:#141a2a"
format = '[[($all_status$ahead_behind )](fg:#0b1020 bg:#1b2338)]($style)'
conflicted = "â€¼"
ahead      = "â‡¡"
behind     = "â‡£"
diverged   = "â†•ï¸"
up_to_date = "âœ“"
stashed    = "ïƒ‡ "
modified   = "â—"
staged     = "[++\\($count\\)](green)"
renamed    = "âœ"
deleted    = "âœ–"

[git_branch]
style  = "bg:#1b2338"
format = '[[ $symbol $branch ](fg:#a78bfa bg:#1b2338)]($style)'

[character]
success_symbol = "[âœ”](fg:#a78bfa)"
error_symbol   = "[âœ–](fg:#7aa2f7)"

[nodejs]
symbol = "îœ˜"
style  = "bg:#141a2a"
format = '[[ $symbol ($version) ](fg:#a78bfa bg:#141a2a)]($style)'

[rust]
symbol = "î¨"
style  = "bg:#141a2a"
format = '[[ $symbol ($version) ](fg:#a78bfa bg:#141a2a)]($style)'

[golang]
symbol = "î˜§"
style  = "bg:#141a2a"
format = '[[ $symbol ($version) ](fg:#a78bfa bg:#141a2a)]($style)'

[python]
symbol = "î˜†"
style  = "bg:#141a2a"
format = '[[ $symbol ($version) ](fg:#a78bfa bg:#141a2a)]($style)'

[php]
symbol = "î˜ˆ"
style  = "bg:#141a2a"
format = '[[ $symbol ($version) ](fg:#a78bfa bg:#141a2a)]($style)'

[time]
disabled    = false
time_format = "%R"
style       = "bg:#0b1020"
format      = '[[ $time ](fg:#7aa2f7 bg:#0b1020)]($style)'

[os]
disabled = false
style    = "fg:#0b1020 bg:#7aa2f7"

[os.symbols]
Windows = "ó°²"
Ubuntu  = "ó°Œ½ "
SUSE    = "ïŒ”"
Raspbian= "ó°¿"
Mint    = "ó°£­"
Macos   = "î˜Ÿ"
Manjaro = "ïŒ’"
Linux   = "ó°Œ½"
Gentoo  = "ó°£¨"
Fedora  = "ó°£›"
Alpine  = "ïŒ€"
Amazon  = "ï‰°"
Android = "îœ"
Arch    = "ó°£‡"
Artix   = "ó°£‡"
CentOS  = "ïŒ„"
Debian  = "ó°£š"
Redhat  = "ó±„›"
RedHatEnterprise = "ó±„›"

