format = """
[î‚¶](#a18aff)\
$os\
[](bg:#a18aff fg:#0d0d0d)\
[î‚´](bg:#ff9abf fg:#a18aff)\
$directory\
[î‚´](fg:#ff9abf bg:#ffb784)\
$git_branch\
$git_status\
[î‚´](fg:#ffb784 bg:#7ac7f6)\
$nodejs\
$rust\
$golang\
$zsh\
$vscode\
$python\
$php\
[î‚´](fg:#7ac7f6 bg:#2b2d42)\
$time\
[î‚´ ](fg:#2b2d42)\
\n$character"""

[directory]
style = "fg:#fefefe bg:#ff9abf"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"work" = "ğŸ—‚ï¸ "

[git_status]
style = "fg:#2b2d42 bg:#7ac7f6"
format = '[[($all_status$ahead_behind )](fg:#2b2d42 bg:#ffb784)]($style)'
conflicted = 'â€¼'
ahead = 'â‡¡'
behind = 'â‡£'
diverged = 'â†•ï¸'
up_to_date = 'âœ“'
stashed = "ïƒ‡ "
modified = 'â—'
staged = '[++\($count\)](green)'
renamed = 'âœ'
deleted = 'âœ–'

[git_branch]
style = "bg:#ffb784"
format = '[[ $symbol $branch ](fg:#2b2d42 bg:#ffb784)]($style)'

[character]
success_symbol = "[âœ”](fg:#7ac7f6)"
error_symbol = "[âœ–](fg:#ff9abf)"

[nodejs]
symbol = "îœ˜"
style = "bg:#7ac7f6"
format = '[[ $symbol ($version) ](fg:#2b2d42 bg:#7ac7f6)]($style)'

[rust]
symbol = "î¨"
style = "bg:#7ac7f6"
format = '[[ $symbol ($version) ](fg:#2b2d42 bg:#7ac7f6)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#7ac7f6"
format = '[[ $symbol ($version) ](fg:#2b2d42 bg:#7ac7f6)]($style)'

[python]
symbol = "î˜†"
style = "bg:#7ac7f6"
format = '[[ $symbol ($version) ](fg:#2b2d42 bg:#7ac7f6)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#7ac7f6"
format = '[[ $symbol ($version) ](fg:#2b2d42 bg:#7ac7f6)]($style)'

[time]
disabled = false
time_format = "%R"
format = '[[ $time ](fg:#ff9abf bg:#2b2d42)]($style)'

[os]
disabled = false
style = "fg:#ffffff bg:#a18aff"

[os.symbols]
Linux = "ó°Œ½"
Macos = "î˜Ÿ"
Windows = "ó°²"
Ubuntu = "ó°Œ½ "
Arch = "ó°£‡"
