format = """
[î‚¶](#e06c75)\
$os\
[](bg:#e06c75 fg:#090c0c)\
[î‚´](bg:#f07b85 fg:#e06c75)\
$directory\
[î‚´](fg:#f07b85 bg:#b54048)\
$git_branch\
$git_status\
[î‚´](fg:#b54048 bg:#8c2b2f)\
$nodejs\
$rust\
$golang\
$zsh\
$vscode\
$python\
$php\
[î‚´](fg:#8c2b2f bg:#4a1619)\
$time\
[î‚´ ](fg:#4a1619)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#f07b85"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"work" = "ğŸ—‚ï¸ "
"personal" = "ğŸ§‘â€ğŸ’» "
"trash" = "ğŸ—‘ï¸ "
"tmp" = "âš™ï¸ "

[git_status]
style = "fg:#8c2b2f bg:#4a1619"
format = '[[($all_status$ahead_behind )](fg:#e06c75 bg:#b54048)]($style)'
conflicted = 'â€¼'
ahead = 'â‡¡'
behind = 'â‡£'
diverged = 'â†•ï¸'
up_to_date = 'âœ“'
untracked = ''
stashed = "ïƒ‡ "
modified = 'â—'
staged = '[++\($count\)](green)'
renamed = 'âœ'
deleted = 'âœ–'

[git_branch]
style = "bg:#b54048"
format = '[[ $symbol $branch ](fg:#f07b85 bg:#b54048)]($style)'

[character]
success_symbol = "[âœ”](fg:#82aaff)"
error_symbol = "[âœ–](fg:#c792ea)"

[nodejs]
symbol = "îœ˜"
style = "bg:#8c2b2f"
format = '[[ $symbol ($version) ](fg:#f07b85 bg:#8c2b2f)]($style)'

[rust]
symbol = "î¨"
style = "bg:#8c2b2f"
format = '[[ $symbol ($version) ](fg:#f07b85 bg:#8c2b2f)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#8c2b2f"
format = '[[ $symbol ($version) ](fg:#f07b85 bg:#8c2b2f)]($style)'

[python]
symbol = "î˜†"
style = "bg:#8c2b2f"
format = '[[ $symbol ($version) ](fg:#f07b85 bg:#8c2b2f)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#8c2b2f"
format = '[[ $symbol ($version) ](fg:#f07b85 bg:#8c2b2f)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[ $time ](fg:#e06c75 bg:#4a1619)]($style)'

[os]
disabled = false
style = "fg:#e0e0e0 bg:#e06c75"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°Œ½ "
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "î˜Ÿ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
